# Generated by Django 5.1.3 on 2025-12-08 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exercise_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(default='other', max_length=50),
        ),
        migrations.CreateModel(
            name='CardioType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardio_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CardioEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distance (optional, in miles or km)', max_digits=7, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardio_entries', to='workouts.workout')),
                ('cardio_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='workouts.cardiotype')),
            ],
            options={
                'verbose_name_plural': 'Cardio entries',
                'ordering': ['id'],
            },
        ),
    ]
